// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Filter_HW_Filter_HW,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=255709,HLS_SYN_TPT=130952,HLS_SYN_MEM=42,HLS_SYN_DSP=0,HLS_SYN_FF=7200,HLS_SYN_LUT=8455,HLS_VERSION=2020_2}" *)

module Filter_HW (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_aximm1_AWVALID,
        m_axi_aximm1_AWREADY,
        m_axi_aximm1_AWADDR,
        m_axi_aximm1_AWID,
        m_axi_aximm1_AWLEN,
        m_axi_aximm1_AWSIZE,
        m_axi_aximm1_AWBURST,
        m_axi_aximm1_AWLOCK,
        m_axi_aximm1_AWCACHE,
        m_axi_aximm1_AWPROT,
        m_axi_aximm1_AWQOS,
        m_axi_aximm1_AWREGION,
        m_axi_aximm1_AWUSER,
        m_axi_aximm1_WVALID,
        m_axi_aximm1_WREADY,
        m_axi_aximm1_WDATA,
        m_axi_aximm1_WSTRB,
        m_axi_aximm1_WLAST,
        m_axi_aximm1_WID,
        m_axi_aximm1_WUSER,
        m_axi_aximm1_ARVALID,
        m_axi_aximm1_ARREADY,
        m_axi_aximm1_ARADDR,
        m_axi_aximm1_ARID,
        m_axi_aximm1_ARLEN,
        m_axi_aximm1_ARSIZE,
        m_axi_aximm1_ARBURST,
        m_axi_aximm1_ARLOCK,
        m_axi_aximm1_ARCACHE,
        m_axi_aximm1_ARPROT,
        m_axi_aximm1_ARQOS,
        m_axi_aximm1_ARREGION,
        m_axi_aximm1_ARUSER,
        m_axi_aximm1_RVALID,
        m_axi_aximm1_RREADY,
        m_axi_aximm1_RDATA,
        m_axi_aximm1_RLAST,
        m_axi_aximm1_RID,
        m_axi_aximm1_RUSER,
        m_axi_aximm1_RRESP,
        m_axi_aximm1_BVALID,
        m_axi_aximm1_BREADY,
        m_axi_aximm1_BRESP,
        m_axi_aximm1_BID,
        m_axi_aximm1_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_AXIMM1_ID_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_AXIMM1_DATA_WIDTH = 512;
parameter    C_M_AXI_AXIMM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_USER_VALUE = 0;
parameter    C_M_AXI_AXIMM1_PROT_VALUE = 0;
parameter    C_M_AXI_AXIMM1_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_AXIMM1_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_aximm1_AWVALID;
input   m_axi_aximm1_AWREADY;
output  [C_M_AXI_AXIMM1_ADDR_WIDTH - 1:0] m_axi_aximm1_AWADDR;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_AWID;
output  [7:0] m_axi_aximm1_AWLEN;
output  [2:0] m_axi_aximm1_AWSIZE;
output  [1:0] m_axi_aximm1_AWBURST;
output  [1:0] m_axi_aximm1_AWLOCK;
output  [3:0] m_axi_aximm1_AWCACHE;
output  [2:0] m_axi_aximm1_AWPROT;
output  [3:0] m_axi_aximm1_AWQOS;
output  [3:0] m_axi_aximm1_AWREGION;
output  [C_M_AXI_AXIMM1_AWUSER_WIDTH - 1:0] m_axi_aximm1_AWUSER;
output   m_axi_aximm1_WVALID;
input   m_axi_aximm1_WREADY;
output  [C_M_AXI_AXIMM1_DATA_WIDTH - 1:0] m_axi_aximm1_WDATA;
output  [C_M_AXI_AXIMM1_WSTRB_WIDTH - 1:0] m_axi_aximm1_WSTRB;
output   m_axi_aximm1_WLAST;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_WID;
output  [C_M_AXI_AXIMM1_WUSER_WIDTH - 1:0] m_axi_aximm1_WUSER;
output   m_axi_aximm1_ARVALID;
input   m_axi_aximm1_ARREADY;
output  [C_M_AXI_AXIMM1_ADDR_WIDTH - 1:0] m_axi_aximm1_ARADDR;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_ARID;
output  [7:0] m_axi_aximm1_ARLEN;
output  [2:0] m_axi_aximm1_ARSIZE;
output  [1:0] m_axi_aximm1_ARBURST;
output  [1:0] m_axi_aximm1_ARLOCK;
output  [3:0] m_axi_aximm1_ARCACHE;
output  [2:0] m_axi_aximm1_ARPROT;
output  [3:0] m_axi_aximm1_ARQOS;
output  [3:0] m_axi_aximm1_ARREGION;
output  [C_M_AXI_AXIMM1_ARUSER_WIDTH - 1:0] m_axi_aximm1_ARUSER;
input   m_axi_aximm1_RVALID;
output   m_axi_aximm1_RREADY;
input  [C_M_AXI_AXIMM1_DATA_WIDTH - 1:0] m_axi_aximm1_RDATA;
input   m_axi_aximm1_RLAST;
input  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_RID;
input  [C_M_AXI_AXIMM1_RUSER_WIDTH - 1:0] m_axi_aximm1_RUSER;
input  [1:0] m_axi_aximm1_RRESP;
input   m_axi_aximm1_BVALID;
output   m_axi_aximm1_BREADY;
input  [1:0] m_axi_aximm1_BRESP;
input  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_BID;
input  [C_M_AXI_AXIMM1_BUSER_WIDTH - 1:0] m_axi_aximm1_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] Input_r;
wire   [63:0] Output_r;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    aximm1_AWREADY;
wire    aximm1_WREADY;
wire    aximm1_ARREADY;
wire    aximm1_RVALID;
wire   [511:0] aximm1_RDATA;
wire    aximm1_RLAST;
wire   [0:0] aximm1_RID;
wire   [0:0] aximm1_RUSER;
wire   [1:0] aximm1_RRESP;
wire    aximm1_BVALID;
wire   [1:0] aximm1_BRESP;
wire   [0:0] aximm1_BID;
wire   [0:0] aximm1_BUSER;
wire    Filter_HW_entry3_U0_ap_start;
wire    Filter_HW_entry3_U0_ap_done;
wire    Filter_HW_entry3_U0_ap_continue;
wire    Filter_HW_entry3_U0_ap_idle;
wire    Filter_HW_entry3_U0_ap_ready;
wire   [63:0] Filter_HW_entry3_U0_Input_out_din;
wire    Filter_HW_entry3_U0_Input_out_write;
wire   [63:0] Filter_HW_entry3_U0_Output_out_din;
wire    Filter_HW_entry3_U0_Output_out_write;
wire    read_input3_U0_ap_start;
wire    read_input3_U0_start_full_n;
wire    read_input3_U0_ap_done;
wire    read_input3_U0_ap_continue;
wire    read_input3_U0_ap_idle;
wire    read_input3_U0_ap_ready;
wire    read_input3_U0_start_out;
wire    read_input3_U0_start_write;
wire    read_input3_U0_m_axi_aximm1_AWVALID;
wire   [63:0] read_input3_U0_m_axi_aximm1_AWADDR;
wire   [0:0] read_input3_U0_m_axi_aximm1_AWID;
wire   [31:0] read_input3_U0_m_axi_aximm1_AWLEN;
wire   [2:0] read_input3_U0_m_axi_aximm1_AWSIZE;
wire   [1:0] read_input3_U0_m_axi_aximm1_AWBURST;
wire   [1:0] read_input3_U0_m_axi_aximm1_AWLOCK;
wire   [3:0] read_input3_U0_m_axi_aximm1_AWCACHE;
wire   [2:0] read_input3_U0_m_axi_aximm1_AWPROT;
wire   [3:0] read_input3_U0_m_axi_aximm1_AWQOS;
wire   [3:0] read_input3_U0_m_axi_aximm1_AWREGION;
wire   [0:0] read_input3_U0_m_axi_aximm1_AWUSER;
wire    read_input3_U0_m_axi_aximm1_WVALID;
wire   [511:0] read_input3_U0_m_axi_aximm1_WDATA;
wire   [63:0] read_input3_U0_m_axi_aximm1_WSTRB;
wire    read_input3_U0_m_axi_aximm1_WLAST;
wire   [0:0] read_input3_U0_m_axi_aximm1_WID;
wire   [0:0] read_input3_U0_m_axi_aximm1_WUSER;
wire    read_input3_U0_m_axi_aximm1_ARVALID;
wire   [63:0] read_input3_U0_m_axi_aximm1_ARADDR;
wire   [0:0] read_input3_U0_m_axi_aximm1_ARID;
wire   [31:0] read_input3_U0_m_axi_aximm1_ARLEN;
wire   [2:0] read_input3_U0_m_axi_aximm1_ARSIZE;
wire   [1:0] read_input3_U0_m_axi_aximm1_ARBURST;
wire   [1:0] read_input3_U0_m_axi_aximm1_ARLOCK;
wire   [3:0] read_input3_U0_m_axi_aximm1_ARCACHE;
wire   [2:0] read_input3_U0_m_axi_aximm1_ARPROT;
wire   [3:0] read_input3_U0_m_axi_aximm1_ARQOS;
wire   [3:0] read_input3_U0_m_axi_aximm1_ARREGION;
wire   [0:0] read_input3_U0_m_axi_aximm1_ARUSER;
wire    read_input3_U0_m_axi_aximm1_RREADY;
wire    read_input3_U0_m_axi_aximm1_BREADY;
wire    read_input3_U0_Input_r_read;
wire    read_input3_U0_Output_r_read;
wire   [63:0] read_input3_U0_Output_out_din;
wire    read_input3_U0_Output_out_write;
wire   [7:0] read_input3_U0_inStream_din;
wire    read_input3_U0_inStream_write;
wire    Filter_horizontal_HW_U0_ap_start;
wire    Filter_horizontal_HW_U0_ap_done;
wire    Filter_horizontal_HW_U0_ap_continue;
wire    Filter_horizontal_HW_U0_ap_idle;
wire    Filter_horizontal_HW_U0_ap_ready;
wire    Filter_horizontal_HW_U0_start_out;
wire    Filter_horizontal_HW_U0_start_write;
wire    Filter_horizontal_HW_U0_inStream_read;
wire   [7:0] Filter_horizontal_HW_U0_TempStream_din;
wire    Filter_horizontal_HW_U0_TempStream_write;
wire    Filter_vertical_HW_U0_ap_start;
wire    Filter_vertical_HW_U0_ap_done;
wire    Filter_vertical_HW_U0_ap_continue;
wire    Filter_vertical_HW_U0_ap_idle;
wire    Filter_vertical_HW_U0_ap_ready;
wire    Filter_vertical_HW_U0_TempStream_read;
wire   [7:0] Filter_vertical_HW_U0_outStream_din;
wire    Filter_vertical_HW_U0_outStream_write;
wire    write_output_U0_ap_start;
wire    write_output_U0_ap_done;
wire    write_output_U0_ap_continue;
wire    write_output_U0_ap_idle;
wire    write_output_U0_ap_ready;
wire    write_output_U0_m_axi_aximm1_AWVALID;
wire   [63:0] write_output_U0_m_axi_aximm1_AWADDR;
wire   [0:0] write_output_U0_m_axi_aximm1_AWID;
wire   [31:0] write_output_U0_m_axi_aximm1_AWLEN;
wire   [2:0] write_output_U0_m_axi_aximm1_AWSIZE;
wire   [1:0] write_output_U0_m_axi_aximm1_AWBURST;
wire   [1:0] write_output_U0_m_axi_aximm1_AWLOCK;
wire   [3:0] write_output_U0_m_axi_aximm1_AWCACHE;
wire   [2:0] write_output_U0_m_axi_aximm1_AWPROT;
wire   [3:0] write_output_U0_m_axi_aximm1_AWQOS;
wire   [3:0] write_output_U0_m_axi_aximm1_AWREGION;
wire   [0:0] write_output_U0_m_axi_aximm1_AWUSER;
wire    write_output_U0_m_axi_aximm1_WVALID;
wire   [511:0] write_output_U0_m_axi_aximm1_WDATA;
wire   [63:0] write_output_U0_m_axi_aximm1_WSTRB;
wire    write_output_U0_m_axi_aximm1_WLAST;
wire   [0:0] write_output_U0_m_axi_aximm1_WID;
wire   [0:0] write_output_U0_m_axi_aximm1_WUSER;
wire    write_output_U0_m_axi_aximm1_ARVALID;
wire   [63:0] write_output_U0_m_axi_aximm1_ARADDR;
wire   [0:0] write_output_U0_m_axi_aximm1_ARID;
wire   [31:0] write_output_U0_m_axi_aximm1_ARLEN;
wire   [2:0] write_output_U0_m_axi_aximm1_ARSIZE;
wire   [1:0] write_output_U0_m_axi_aximm1_ARBURST;
wire   [1:0] write_output_U0_m_axi_aximm1_ARLOCK;
wire   [3:0] write_output_U0_m_axi_aximm1_ARCACHE;
wire   [2:0] write_output_U0_m_axi_aximm1_ARPROT;
wire   [3:0] write_output_U0_m_axi_aximm1_ARQOS;
wire   [3:0] write_output_U0_m_axi_aximm1_ARREGION;
wire   [0:0] write_output_U0_m_axi_aximm1_ARUSER;
wire    write_output_U0_m_axi_aximm1_RREADY;
wire    write_output_U0_m_axi_aximm1_BREADY;
wire    write_output_U0_out_r_read;
wire    write_output_U0_outStream_read;
wire    ap_sync_continue;
wire    Input_c_full_n;
wire   [63:0] Input_c_dout;
wire    Input_c_empty_n;
wire    Output_c1_full_n;
wire   [63:0] Output_c1_dout;
wire    Output_c1_empty_n;
wire    Output_c_full_n;
wire   [63:0] Output_c_dout;
wire    Output_c_empty_n;
wire    inStream_full_n;
wire   [7:0] inStream_dout;
wire    inStream_empty_n;
wire    TempStream_full_n;
wire   [7:0] TempStream_dout;
wire    TempStream_empty_n;
wire    outStream_full_n;
wire   [7:0] outStream_dout;
wire    outStream_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Filter_HW_entry3_U0_ap_ready;
wire    ap_sync_Filter_HW_entry3_U0_ap_ready;
reg    ap_sync_reg_read_input3_U0_ap_ready;
wire    ap_sync_read_input3_U0_ap_ready;
wire    Filter_HW_entry3_U0_start_full_n;
wire    Filter_HW_entry3_U0_start_write;
wire   [0:0] start_for_Filter_horizontal_HW_U0_din;
wire    start_for_Filter_horizontal_HW_U0_full_n;
wire   [0:0] start_for_Filter_horizontal_HW_U0_dout;
wire    start_for_Filter_horizontal_HW_U0_empty_n;
wire   [0:0] start_for_write_output_U0_din;
wire    start_for_write_output_U0_full_n;
wire   [0:0] start_for_write_output_U0_dout;
wire    start_for_write_output_U0_empty_n;
wire   [0:0] start_for_Filter_vertical_HW_U0_din;
wire    start_for_Filter_vertical_HW_U0_full_n;
wire   [0:0] start_for_Filter_vertical_HW_U0_dout;
wire    start_for_Filter_vertical_HW_U0_empty_n;
wire    Filter_vertical_HW_U0_start_full_n;
wire    Filter_vertical_HW_U0_start_write;
wire    write_output_U0_start_full_n;
wire    write_output_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_Filter_HW_entry3_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_input3_U0_ap_ready = 1'b0;
end

Filter_HW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .Input_r(Input_r),
    .Output_r(Output_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

Filter_HW_aximm1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_AXIMM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_AXIMM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_AXIMM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_AXIMM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_AXIMM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_AXIMM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_AXIMM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_AXIMM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_AXIMM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_AXIMM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_AXIMM1_CACHE_VALUE ))
aximm1_m_axi_U(
    .AWVALID(m_axi_aximm1_AWVALID),
    .AWREADY(m_axi_aximm1_AWREADY),
    .AWADDR(m_axi_aximm1_AWADDR),
    .AWID(m_axi_aximm1_AWID),
    .AWLEN(m_axi_aximm1_AWLEN),
    .AWSIZE(m_axi_aximm1_AWSIZE),
    .AWBURST(m_axi_aximm1_AWBURST),
    .AWLOCK(m_axi_aximm1_AWLOCK),
    .AWCACHE(m_axi_aximm1_AWCACHE),
    .AWPROT(m_axi_aximm1_AWPROT),
    .AWQOS(m_axi_aximm1_AWQOS),
    .AWREGION(m_axi_aximm1_AWREGION),
    .AWUSER(m_axi_aximm1_AWUSER),
    .WVALID(m_axi_aximm1_WVALID),
    .WREADY(m_axi_aximm1_WREADY),
    .WDATA(m_axi_aximm1_WDATA),
    .WSTRB(m_axi_aximm1_WSTRB),
    .WLAST(m_axi_aximm1_WLAST),
    .WID(m_axi_aximm1_WID),
    .WUSER(m_axi_aximm1_WUSER),
    .ARVALID(m_axi_aximm1_ARVALID),
    .ARREADY(m_axi_aximm1_ARREADY),
    .ARADDR(m_axi_aximm1_ARADDR),
    .ARID(m_axi_aximm1_ARID),
    .ARLEN(m_axi_aximm1_ARLEN),
    .ARSIZE(m_axi_aximm1_ARSIZE),
    .ARBURST(m_axi_aximm1_ARBURST),
    .ARLOCK(m_axi_aximm1_ARLOCK),
    .ARCACHE(m_axi_aximm1_ARCACHE),
    .ARPROT(m_axi_aximm1_ARPROT),
    .ARQOS(m_axi_aximm1_ARQOS),
    .ARREGION(m_axi_aximm1_ARREGION),
    .ARUSER(m_axi_aximm1_ARUSER),
    .RVALID(m_axi_aximm1_RVALID),
    .RREADY(m_axi_aximm1_RREADY),
    .RDATA(m_axi_aximm1_RDATA),
    .RLAST(m_axi_aximm1_RLAST),
    .RID(m_axi_aximm1_RID),
    .RUSER(m_axi_aximm1_RUSER),
    .RRESP(m_axi_aximm1_RRESP),
    .BVALID(m_axi_aximm1_BVALID),
    .BREADY(m_axi_aximm1_BREADY),
    .BRESP(m_axi_aximm1_BRESP),
    .BID(m_axi_aximm1_BID),
    .BUSER(m_axi_aximm1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(read_input3_U0_m_axi_aximm1_ARVALID),
    .I_ARREADY(aximm1_ARREADY),
    .I_ARADDR(read_input3_U0_m_axi_aximm1_ARADDR),
    .I_ARID(read_input3_U0_m_axi_aximm1_ARID),
    .I_ARLEN(read_input3_U0_m_axi_aximm1_ARLEN),
    .I_ARSIZE(read_input3_U0_m_axi_aximm1_ARSIZE),
    .I_ARLOCK(read_input3_U0_m_axi_aximm1_ARLOCK),
    .I_ARCACHE(read_input3_U0_m_axi_aximm1_ARCACHE),
    .I_ARQOS(read_input3_U0_m_axi_aximm1_ARQOS),
    .I_ARPROT(read_input3_U0_m_axi_aximm1_ARPROT),
    .I_ARUSER(read_input3_U0_m_axi_aximm1_ARUSER),
    .I_ARBURST(read_input3_U0_m_axi_aximm1_ARBURST),
    .I_ARREGION(read_input3_U0_m_axi_aximm1_ARREGION),
    .I_RVALID(aximm1_RVALID),
    .I_RREADY(read_input3_U0_m_axi_aximm1_RREADY),
    .I_RDATA(aximm1_RDATA),
    .I_RID(aximm1_RID),
    .I_RUSER(aximm1_RUSER),
    .I_RRESP(aximm1_RRESP),
    .I_RLAST(aximm1_RLAST),
    .I_AWVALID(write_output_U0_m_axi_aximm1_AWVALID),
    .I_AWREADY(aximm1_AWREADY),
    .I_AWADDR(write_output_U0_m_axi_aximm1_AWADDR),
    .I_AWID(write_output_U0_m_axi_aximm1_AWID),
    .I_AWLEN(write_output_U0_m_axi_aximm1_AWLEN),
    .I_AWSIZE(write_output_U0_m_axi_aximm1_AWSIZE),
    .I_AWLOCK(write_output_U0_m_axi_aximm1_AWLOCK),
    .I_AWCACHE(write_output_U0_m_axi_aximm1_AWCACHE),
    .I_AWQOS(write_output_U0_m_axi_aximm1_AWQOS),
    .I_AWPROT(write_output_U0_m_axi_aximm1_AWPROT),
    .I_AWUSER(write_output_U0_m_axi_aximm1_AWUSER),
    .I_AWBURST(write_output_U0_m_axi_aximm1_AWBURST),
    .I_AWREGION(write_output_U0_m_axi_aximm1_AWREGION),
    .I_WVALID(write_output_U0_m_axi_aximm1_WVALID),
    .I_WREADY(aximm1_WREADY),
    .I_WDATA(write_output_U0_m_axi_aximm1_WDATA),
    .I_WID(write_output_U0_m_axi_aximm1_WID),
    .I_WUSER(write_output_U0_m_axi_aximm1_WUSER),
    .I_WLAST(write_output_U0_m_axi_aximm1_WLAST),
    .I_WSTRB(write_output_U0_m_axi_aximm1_WSTRB),
    .I_BVALID(aximm1_BVALID),
    .I_BREADY(write_output_U0_m_axi_aximm1_BREADY),
    .I_BRESP(aximm1_BRESP),
    .I_BID(aximm1_BID),
    .I_BUSER(aximm1_BUSER)
);

Filter_HW_Filter_HW_entry3 Filter_HW_entry3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter_HW_entry3_U0_ap_start),
    .ap_done(Filter_HW_entry3_U0_ap_done),
    .ap_continue(Filter_HW_entry3_U0_ap_continue),
    .ap_idle(Filter_HW_entry3_U0_ap_idle),
    .ap_ready(Filter_HW_entry3_U0_ap_ready),
    .Input_r(Input_r),
    .Output_r(Output_r),
    .Input_out_din(Filter_HW_entry3_U0_Input_out_din),
    .Input_out_full_n(Input_c_full_n),
    .Input_out_write(Filter_HW_entry3_U0_Input_out_write),
    .Output_out_din(Filter_HW_entry3_U0_Output_out_din),
    .Output_out_full_n(Output_c1_full_n),
    .Output_out_write(Filter_HW_entry3_U0_Output_out_write)
);

Filter_HW_read_input3 read_input3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_input3_U0_ap_start),
    .start_full_n(read_input3_U0_start_full_n),
    .ap_done(read_input3_U0_ap_done),
    .ap_continue(read_input3_U0_ap_continue),
    .ap_idle(read_input3_U0_ap_idle),
    .ap_ready(read_input3_U0_ap_ready),
    .start_out(read_input3_U0_start_out),
    .start_write(read_input3_U0_start_write),
    .m_axi_aximm1_AWVALID(read_input3_U0_m_axi_aximm1_AWVALID),
    .m_axi_aximm1_AWREADY(1'b0),
    .m_axi_aximm1_AWADDR(read_input3_U0_m_axi_aximm1_AWADDR),
    .m_axi_aximm1_AWID(read_input3_U0_m_axi_aximm1_AWID),
    .m_axi_aximm1_AWLEN(read_input3_U0_m_axi_aximm1_AWLEN),
    .m_axi_aximm1_AWSIZE(read_input3_U0_m_axi_aximm1_AWSIZE),
    .m_axi_aximm1_AWBURST(read_input3_U0_m_axi_aximm1_AWBURST),
    .m_axi_aximm1_AWLOCK(read_input3_U0_m_axi_aximm1_AWLOCK),
    .m_axi_aximm1_AWCACHE(read_input3_U0_m_axi_aximm1_AWCACHE),
    .m_axi_aximm1_AWPROT(read_input3_U0_m_axi_aximm1_AWPROT),
    .m_axi_aximm1_AWQOS(read_input3_U0_m_axi_aximm1_AWQOS),
    .m_axi_aximm1_AWREGION(read_input3_U0_m_axi_aximm1_AWREGION),
    .m_axi_aximm1_AWUSER(read_input3_U0_m_axi_aximm1_AWUSER),
    .m_axi_aximm1_WVALID(read_input3_U0_m_axi_aximm1_WVALID),
    .m_axi_aximm1_WREADY(1'b0),
    .m_axi_aximm1_WDATA(read_input3_U0_m_axi_aximm1_WDATA),
    .m_axi_aximm1_WSTRB(read_input3_U0_m_axi_aximm1_WSTRB),
    .m_axi_aximm1_WLAST(read_input3_U0_m_axi_aximm1_WLAST),
    .m_axi_aximm1_WID(read_input3_U0_m_axi_aximm1_WID),
    .m_axi_aximm1_WUSER(read_input3_U0_m_axi_aximm1_WUSER),
    .m_axi_aximm1_ARVALID(read_input3_U0_m_axi_aximm1_ARVALID),
    .m_axi_aximm1_ARREADY(aximm1_ARREADY),
    .m_axi_aximm1_ARADDR(read_input3_U0_m_axi_aximm1_ARADDR),
    .m_axi_aximm1_ARID(read_input3_U0_m_axi_aximm1_ARID),
    .m_axi_aximm1_ARLEN(read_input3_U0_m_axi_aximm1_ARLEN),
    .m_axi_aximm1_ARSIZE(read_input3_U0_m_axi_aximm1_ARSIZE),
    .m_axi_aximm1_ARBURST(read_input3_U0_m_axi_aximm1_ARBURST),
    .m_axi_aximm1_ARLOCK(read_input3_U0_m_axi_aximm1_ARLOCK),
    .m_axi_aximm1_ARCACHE(read_input3_U0_m_axi_aximm1_ARCACHE),
    .m_axi_aximm1_ARPROT(read_input3_U0_m_axi_aximm1_ARPROT),
    .m_axi_aximm1_ARQOS(read_input3_U0_m_axi_aximm1_ARQOS),
    .m_axi_aximm1_ARREGION(read_input3_U0_m_axi_aximm1_ARREGION),
    .m_axi_aximm1_ARUSER(read_input3_U0_m_axi_aximm1_ARUSER),
    .m_axi_aximm1_RVALID(aximm1_RVALID),
    .m_axi_aximm1_RREADY(read_input3_U0_m_axi_aximm1_RREADY),
    .m_axi_aximm1_RDATA(aximm1_RDATA),
    .m_axi_aximm1_RLAST(aximm1_RLAST),
    .m_axi_aximm1_RID(aximm1_RID),
    .m_axi_aximm1_RUSER(aximm1_RUSER),
    .m_axi_aximm1_RRESP(aximm1_RRESP),
    .m_axi_aximm1_BVALID(1'b0),
    .m_axi_aximm1_BREADY(read_input3_U0_m_axi_aximm1_BREADY),
    .m_axi_aximm1_BRESP(2'd0),
    .m_axi_aximm1_BID(1'd0),
    .m_axi_aximm1_BUSER(1'd0),
    .Input_r_dout(Input_c_dout),
    .Input_r_empty_n(Input_c_empty_n),
    .Input_r_read(read_input3_U0_Input_r_read),
    .Output_r_dout(Output_c1_dout),
    .Output_r_empty_n(Output_c1_empty_n),
    .Output_r_read(read_input3_U0_Output_r_read),
    .Output_out_din(read_input3_U0_Output_out_din),
    .Output_out_full_n(Output_c_full_n),
    .Output_out_write(read_input3_U0_Output_out_write),
    .inStream_din(read_input3_U0_inStream_din),
    .inStream_full_n(inStream_full_n),
    .inStream_write(read_input3_U0_inStream_write)
);

Filter_HW_Filter_horizontal_HW Filter_horizontal_HW_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter_horizontal_HW_U0_ap_start),
    .start_full_n(start_for_Filter_vertical_HW_U0_full_n),
    .ap_done(Filter_horizontal_HW_U0_ap_done),
    .ap_continue(Filter_horizontal_HW_U0_ap_continue),
    .ap_idle(Filter_horizontal_HW_U0_ap_idle),
    .ap_ready(Filter_horizontal_HW_U0_ap_ready),
    .start_out(Filter_horizontal_HW_U0_start_out),
    .start_write(Filter_horizontal_HW_U0_start_write),
    .inStream_dout(inStream_dout),
    .inStream_empty_n(inStream_empty_n),
    .inStream_read(Filter_horizontal_HW_U0_inStream_read),
    .TempStream_din(Filter_horizontal_HW_U0_TempStream_din),
    .TempStream_full_n(TempStream_full_n),
    .TempStream_write(Filter_horizontal_HW_U0_TempStream_write)
);

Filter_HW_Filter_vertical_HW Filter_vertical_HW_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter_vertical_HW_U0_ap_start),
    .ap_done(Filter_vertical_HW_U0_ap_done),
    .ap_continue(Filter_vertical_HW_U0_ap_continue),
    .ap_idle(Filter_vertical_HW_U0_ap_idle),
    .ap_ready(Filter_vertical_HW_U0_ap_ready),
    .TempStream_dout(TempStream_dout),
    .TempStream_empty_n(TempStream_empty_n),
    .TempStream_read(Filter_vertical_HW_U0_TempStream_read),
    .outStream_din(Filter_vertical_HW_U0_outStream_din),
    .outStream_full_n(outStream_full_n),
    .outStream_write(Filter_vertical_HW_U0_outStream_write)
);

Filter_HW_write_output write_output_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_output_U0_ap_start),
    .ap_done(write_output_U0_ap_done),
    .ap_continue(write_output_U0_ap_continue),
    .ap_idle(write_output_U0_ap_idle),
    .ap_ready(write_output_U0_ap_ready),
    .m_axi_aximm1_AWVALID(write_output_U0_m_axi_aximm1_AWVALID),
    .m_axi_aximm1_AWREADY(aximm1_AWREADY),
    .m_axi_aximm1_AWADDR(write_output_U0_m_axi_aximm1_AWADDR),
    .m_axi_aximm1_AWID(write_output_U0_m_axi_aximm1_AWID),
    .m_axi_aximm1_AWLEN(write_output_U0_m_axi_aximm1_AWLEN),
    .m_axi_aximm1_AWSIZE(write_output_U0_m_axi_aximm1_AWSIZE),
    .m_axi_aximm1_AWBURST(write_output_U0_m_axi_aximm1_AWBURST),
    .m_axi_aximm1_AWLOCK(write_output_U0_m_axi_aximm1_AWLOCK),
    .m_axi_aximm1_AWCACHE(write_output_U0_m_axi_aximm1_AWCACHE),
    .m_axi_aximm1_AWPROT(write_output_U0_m_axi_aximm1_AWPROT),
    .m_axi_aximm1_AWQOS(write_output_U0_m_axi_aximm1_AWQOS),
    .m_axi_aximm1_AWREGION(write_output_U0_m_axi_aximm1_AWREGION),
    .m_axi_aximm1_AWUSER(write_output_U0_m_axi_aximm1_AWUSER),
    .m_axi_aximm1_WVALID(write_output_U0_m_axi_aximm1_WVALID),
    .m_axi_aximm1_WREADY(aximm1_WREADY),
    .m_axi_aximm1_WDATA(write_output_U0_m_axi_aximm1_WDATA),
    .m_axi_aximm1_WSTRB(write_output_U0_m_axi_aximm1_WSTRB),
    .m_axi_aximm1_WLAST(write_output_U0_m_axi_aximm1_WLAST),
    .m_axi_aximm1_WID(write_output_U0_m_axi_aximm1_WID),
    .m_axi_aximm1_WUSER(write_output_U0_m_axi_aximm1_WUSER),
    .m_axi_aximm1_ARVALID(write_output_U0_m_axi_aximm1_ARVALID),
    .m_axi_aximm1_ARREADY(1'b0),
    .m_axi_aximm1_ARADDR(write_output_U0_m_axi_aximm1_ARADDR),
    .m_axi_aximm1_ARID(write_output_U0_m_axi_aximm1_ARID),
    .m_axi_aximm1_ARLEN(write_output_U0_m_axi_aximm1_ARLEN),
    .m_axi_aximm1_ARSIZE(write_output_U0_m_axi_aximm1_ARSIZE),
    .m_axi_aximm1_ARBURST(write_output_U0_m_axi_aximm1_ARBURST),
    .m_axi_aximm1_ARLOCK(write_output_U0_m_axi_aximm1_ARLOCK),
    .m_axi_aximm1_ARCACHE(write_output_U0_m_axi_aximm1_ARCACHE),
    .m_axi_aximm1_ARPROT(write_output_U0_m_axi_aximm1_ARPROT),
    .m_axi_aximm1_ARQOS(write_output_U0_m_axi_aximm1_ARQOS),
    .m_axi_aximm1_ARREGION(write_output_U0_m_axi_aximm1_ARREGION),
    .m_axi_aximm1_ARUSER(write_output_U0_m_axi_aximm1_ARUSER),
    .m_axi_aximm1_RVALID(1'b0),
    .m_axi_aximm1_RREADY(write_output_U0_m_axi_aximm1_RREADY),
    .m_axi_aximm1_RDATA(512'd0),
    .m_axi_aximm1_RLAST(1'b0),
    .m_axi_aximm1_RID(1'd0),
    .m_axi_aximm1_RUSER(1'd0),
    .m_axi_aximm1_RRESP(2'd0),
    .m_axi_aximm1_BVALID(aximm1_BVALID),
    .m_axi_aximm1_BREADY(write_output_U0_m_axi_aximm1_BREADY),
    .m_axi_aximm1_BRESP(aximm1_BRESP),
    .m_axi_aximm1_BID(aximm1_BID),
    .m_axi_aximm1_BUSER(aximm1_BUSER),
    .out_r_dout(Output_c_dout),
    .out_r_empty_n(Output_c_empty_n),
    .out_r_read(write_output_U0_out_r_read),
    .outStream_dout(outStream_dout),
    .outStream_empty_n(outStream_empty_n),
    .outStream_read(write_output_U0_outStream_read)
);

Filter_HW_fifo_w64_d2_S Input_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter_HW_entry3_U0_Input_out_din),
    .if_full_n(Input_c_full_n),
    .if_write(Filter_HW_entry3_U0_Input_out_write),
    .if_dout(Input_c_dout),
    .if_empty_n(Input_c_empty_n),
    .if_read(read_input3_U0_Input_r_read)
);

Filter_HW_fifo_w64_d2_S Output_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter_HW_entry3_U0_Output_out_din),
    .if_full_n(Output_c1_full_n),
    .if_write(Filter_HW_entry3_U0_Output_out_write),
    .if_dout(Output_c1_dout),
    .if_empty_n(Output_c1_empty_n),
    .if_read(read_input3_U0_Output_r_read)
);

Filter_HW_fifo_w64_d4_S Output_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input3_U0_Output_out_din),
    .if_full_n(Output_c_full_n),
    .if_write(read_input3_U0_Output_out_write),
    .if_dout(Output_c_dout),
    .if_empty_n(Output_c_empty_n),
    .if_read(write_output_U0_out_r_read)
);

Filter_HW_fifo_w8_d32_S inStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input3_U0_inStream_din),
    .if_full_n(inStream_full_n),
    .if_write(read_input3_U0_inStream_write),
    .if_dout(inStream_dout),
    .if_empty_n(inStream_empty_n),
    .if_read(Filter_horizontal_HW_U0_inStream_read)
);

Filter_HW_fifo_w8_d32_S TempStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter_horizontal_HW_U0_TempStream_din),
    .if_full_n(TempStream_full_n),
    .if_write(Filter_horizontal_HW_U0_TempStream_write),
    .if_dout(TempStream_dout),
    .if_empty_n(TempStream_empty_n),
    .if_read(Filter_vertical_HW_U0_TempStream_read)
);

Filter_HW_fifo_w8_d32_S outStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter_vertical_HW_U0_outStream_din),
    .if_full_n(outStream_full_n),
    .if_write(Filter_vertical_HW_U0_outStream_write),
    .if_dout(outStream_dout),
    .if_empty_n(outStream_empty_n),
    .if_read(write_output_U0_outStream_read)
);

Filter_HW_start_for_Filter_horizontal_HW_U0 start_for_Filter_horizontal_HW_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Filter_horizontal_HW_U0_din),
    .if_full_n(start_for_Filter_horizontal_HW_U0_full_n),
    .if_write(read_input3_U0_start_write),
    .if_dout(start_for_Filter_horizontal_HW_U0_dout),
    .if_empty_n(start_for_Filter_horizontal_HW_U0_empty_n),
    .if_read(Filter_horizontal_HW_U0_ap_ready)
);

Filter_HW_start_for_write_output_U0 start_for_write_output_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_output_U0_din),
    .if_full_n(start_for_write_output_U0_full_n),
    .if_write(read_input3_U0_start_write),
    .if_dout(start_for_write_output_U0_dout),
    .if_empty_n(start_for_write_output_U0_empty_n),
    .if_read(write_output_U0_ap_ready)
);

Filter_HW_start_for_Filter_vertical_HW_U0 start_for_Filter_vertical_HW_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Filter_vertical_HW_U0_din),
    .if_full_n(start_for_Filter_vertical_HW_U0_full_n),
    .if_write(Filter_horizontal_HW_U0_start_write),
    .if_dout(start_for_Filter_vertical_HW_U0_dout),
    .if_empty_n(start_for_Filter_vertical_HW_U0_empty_n),
    .if_read(Filter_vertical_HW_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Filter_HW_entry3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Filter_HW_entry3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Filter_HW_entry3_U0_ap_ready <= ap_sync_Filter_HW_entry3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read_input3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_input3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_input3_U0_ap_ready <= ap_sync_read_input3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign Filter_HW_entry3_U0_ap_continue = 1'b1;

assign Filter_HW_entry3_U0_ap_start = ((ap_sync_reg_Filter_HW_entry3_U0_ap_ready ^ 1'b1) & ap_start);

assign Filter_HW_entry3_U0_start_full_n = 1'b1;

assign Filter_HW_entry3_U0_start_write = 1'b0;

assign Filter_horizontal_HW_U0_ap_continue = 1'b1;

assign Filter_horizontal_HW_U0_ap_start = start_for_Filter_horizontal_HW_U0_empty_n;

assign Filter_vertical_HW_U0_ap_continue = 1'b1;

assign Filter_vertical_HW_U0_ap_start = start_for_Filter_vertical_HW_U0_empty_n;

assign Filter_vertical_HW_U0_start_full_n = 1'b1;

assign Filter_vertical_HW_U0_start_write = 1'b0;

assign ap_done = write_output_U0_ap_done;

assign ap_idle = (write_output_U0_ap_idle & read_input3_U0_ap_idle & Filter_vertical_HW_U0_ap_idle & Filter_horizontal_HW_U0_ap_idle & Filter_HW_entry3_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_Filter_HW_entry3_U0_ap_ready = (ap_sync_reg_Filter_HW_entry3_U0_ap_ready | Filter_HW_entry3_U0_ap_ready);

assign ap_sync_continue = ap_continue;

assign ap_sync_done = write_output_U0_ap_done;

assign ap_sync_read_input3_U0_ap_ready = (read_input3_U0_ap_ready | ap_sync_reg_read_input3_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_input3_U0_ap_ready & ap_sync_Filter_HW_entry3_U0_ap_ready);

assign read_input3_U0_ap_continue = 1'b1;

assign read_input3_U0_ap_start = ((ap_sync_reg_read_input3_U0_ap_ready ^ 1'b1) & ap_start);

assign read_input3_U0_start_full_n = (start_for_write_output_U0_full_n & start_for_Filter_horizontal_HW_U0_full_n);

assign start_for_Filter_horizontal_HW_U0_din = 1'b1;

assign start_for_Filter_vertical_HW_U0_din = 1'b1;

assign start_for_write_output_U0_din = 1'b1;

assign write_output_U0_ap_continue = ap_continue;

assign write_output_U0_ap_start = start_for_write_output_U0_empty_n;

assign write_output_U0_start_full_n = 1'b1;

assign write_output_U0_start_write = 1'b0;

endmodule //Filter_HW
